### ISSUE TITLE
[BUG] ImportError: cannot import name 'filters' from 'pyrogram'

### ISSUE THREAD

**Issue by ivan-bryliant** [FayasNoushad/Telegraph-Uploader-Bot#1]
from pyrogram import Client, filters

 ImportError: cannot import name 'filters' from 'pyrogram' (C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\__init__.py)

**Comment by ivan-bryliant** [comment]
sorry, didn't understand the version pyrogram

**Comment by ivan-bryliant** [comment]
writes api error, but it is definitely correct

`AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup`

**Comment by fayasnoushad** [comment]
Please install new version and try
